package com.learn.paymentservice.repository;

import com.learn.paymentservice.entity.OutboxEvent;
import org.springframework.data.jpa.repository.JpaRepository;
import org.springframework.stereotype.Repository;

import java.util.List;

/**
 * Repository for OutboxEvent entity
 * 
 * EDUCATIONAL NOTE - Outbox Repository
 * 
 * This repository is critical for the Transactional Outbox pattern.
 * It allows us to:
 * 1. Save events in the same transaction as business data
 * 2. Query unpublished events for eventual publishing
 */
@Repository
public interface OutboxRepository extends JpaRepository<OutboxEvent, Long> {

  /**
   * Find all unpublished events
   * Used by OutboxPublisher to find events that need to be sent to Kafka
   * 
   * Query generated by Spring Data JPA:
   * SELECT * FROM outbox_events WHERE published = false ORDER BY created_at ASC
   */
  List<OutboxEvent> findByPublishedFalseOrderByCreatedAtAsc();

  /**
   * Count unpublished events
   * Useful for monitoring/metrics
   */
  long countByPublishedFalse();
}
